#!/bin/bash

set -e

ticks=50000
team1=my
team2=old
team_size=3

log=out/test-log.txt
if [ -f $log ];
then
    mv $log $log.bak
else
    mkdir -p `dirname $log`
fi

for seed in {100..149}
do
    java -jar dist/russianaicup.jar $team1 $team2 $team_size $ticks $seed | sed "s/^/$seed /" | tee -a $log
done

for seed in {150..199}
do
    java -jar dist/russianaicup.jar $team2 $team1 $team_size $ticks $seed | sed "s/^/$seed /" | tee -a $log
done
