#!/bin/bash

set -e

java -jar dist/russianaicup.jar my old 100000 123456 -3 | sed "s/^/my 3x3 old /"
java -jar dist/russianaicup.jar old my 100000 456789 -3 | sed "s/^/old 3x3 my /"
java -jar dist/russianaicup.jar my old 100000 123456 | sed "s/^/my 2x2 old /"
java -jar dist/russianaicup.jar old my 100000 456789 | sed "s/^/old 2x2 my /"

ticks=100000
team1=my
team2=old

log=out/test-log.txt
if [ -f $log ];
then
    mv $log $log.bak
else
    mkdir -p `dirname $log`
fi

for seed in {100..149}
do
    java -jar dist/russianaicup.jar $team1 $team2 $ticks $seed -3 | sed "s/^/$seed /" | tee -a $log
done

for seed in {150..199}
do
    java -jar dist/russianaicup.jar $team2 $team1 $ticks $seed -3 | sed "s/^/$seed /" | tee -a $log
done
